# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic

from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AccessToken(UniversalBaseModel):
    id: typing.Optional[int] = None
    name: typing.Optional[str] = None
    scopes: typing.Optional[typing.List[str]] = None
    sha1: typing.Optional[str] = None
    token_last_eight: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
