# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic

from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CreateWikiPageOptions(UniversalBaseModel):
    """
    CreateWikiPageOptions form for creating wiki
    """

    content_base64: typing.Optional[str] = pydantic.Field(default=None)
    """
    content must be base64 encoded
    """

    message: typing.Optional[str] = pydantic.Field(default=None)
    """
    optional commit message summarizing the change
    """

    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    page title. leave empty to keep unchanged
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
