# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions

from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class PackageFile(UniversalBaseModel):
    """
    PackageFile represents a package file
    """

    size: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="Size"), pydantic.Field(alias="Size")
    ] = None
    id: typing.Optional[int] = None
    md5: typing.Optional[str] = None
    name: typing.Optional[str] = None
    sha1: typing.Optional[str] = None
    sha256: typing.Optional[str] = None
    sha512: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
